### ISSUE TITLE
Surprise reboot

### ISSUE THREAD

**Issue by dghan0219** [transmitterdan/s2spice#2]
I ran some tests of LIB files created with S2SPICE 1.01 and the new GUI version and the files compare.  The GUI version adds some minor formatting that makes the LIB file easier to read, which is nice.

What I did not like is that the installer rebooted Windows without warning.  This may be coming from the Microsoft libraries that are installed first.  Is there a way to stop this?  If not, add a warning about a reboot so that users have time to gracefully close programs.

**Comment by transmitterdan** [comment]
It may be the automatic Microsoft installer that creates the C runtime libraries.  That is downloaded by the installer if it's not already present in your configuration.  I don't know why Microsoft does not give a warning themselves.  I will add this as an enhancement request.

**Comment by transmitterdan** [comment]
I think this commit (06e1c2170c9dd113005448164f33bae997fbee0b) will fix the reboot issue.  Uninstall previous version then try installing V1.0.1 using link in README.md.

**Comment by dghan0219** [comment]
I would have to uninstall the C++ libraries to test this, which I don't want to do because then I'd have to reboot many times (the uninstall and then the new install).  Uninstalling S2SPICE and then installing it works fine, although the installer complains that the path is too long to add to the environment even though the path to S2SPICE isn't that long.  I noticed you now have a transmitterdan folder.  You can shorten the path somewhat by using %ProgramFiles(x86)% for C:\Program Files (x86).

It would be nice to have the version number in the About screen.

**Comment by transmitterdan** [comment]
The V1.0.1 version brings it's own local C library files.  It should not use the installed ones.
