### ISSUE TITLE
Version 1.0.3 not finding its own DLL files

### ISSUE THREAD

**Issue by dghan0219** [transmitterdan/s2spice#4]
Version 1.0.3 will not run and complains that it can't find the DLL files that are in C:\Program Files (x86)\transmitterdan\s2spice\bin.

**Comment by dghan0219** [comment]
P.S. All the DLL files are in C:\Program Files (x86)\transmitterdan\s2spice\bin in case you thought they were missing.

**Comment by transmitterdan** [comment]
Hmmm, finding DLLs is a Windows thing. Not sure how the program itself can not find the DLLs. Which specific DLL can it not find? Or does it just fail silently?

**Comment by transmitterdan** [comment]
It may be that the policy on your system is to not use DLLs from the exe folder.  You can try installing the C runtime from Microsoft: https://aka.ms/vs/17/release/vc_redist.x86.exe

**Comment by transmitterdan** [comment]
Please download again the release.  It should find the dll now.

**Comment by dghan0219** [comment]
The new version 1.0.3 works.
